kind: pipeline
type: docker
name: custom-paper-patch

steps:
- name: build
  image: maven:3-jdk-8
  commands:
  - apk add --no-cache patch
  - git clone https://github.com/PaperMC/Paper.git
  - cd Paper
  - ./paper jar